from .logging_setup import logger

LANGUAGES = {
    "Automatic detection": "Automatic detection",
    "Arabic (ar)": "ar",
    "Chinese (zh)": "zh",
    "Czech (cs)": "cs",
    "Danish (da)": "da",
    "Dutch (nl)": "nl",
    "English (en)": "en",
    "Finnish (fi)": "fi",
    "French (fr)": "fr",
    "German (de)": "de",
    "Greek (el)": "el",
    "Hebrew (he)": "he",
    "Hungarian (hu)": "hu",
    "Italian (it)": "it",
    "Japanese (ja)": "ja",
    "Korean (ko)": "ko",
    "Persian (fa)": "fa",
    "Polish (pl)": "pl",
    "Portuguese (pt)": "pt",
    "Russian (ru)": "ru",
    "Spanish (es)": "es",
    "Turkish (tr)": "tr",
    "Ukrainian (uk)": "uk",
    "Urdu (ur)": "ur",
    "Vietnamese (vi)": "vi",
    "Hindi (hi)": "hi",
    "Indonesian (id)": "id",
    "Bengali (bn)": "bn",
    "Telugu (te)": "te",
    "Marathi (mr)": "mr",
    "Tamil (ta)": "ta",
    "Javanese (jw|jv)": "jw",
    "Catalan (ca)": "ca",
    "Nepali (ne)": "ne",
    "Thai (th)": "th",
}
LANGUAGES_LIST = list(LANGUAGES.keys())

EXTRA_ALIGN = {
    "id": "indonesian-nlp/wav2vec2-large-xlsr-indonesian",
    "bn": "arijitx/wav2vec2-large-xlsr-bengali",
    "mr": "sumedh/wav2vec2-large-xlsr-marathi",
    "ta": "Amrrs/wav2vec2-large-xlsr-53-tamil",
    "jw": "cahya/wav2vec2-large-xlsr-javanese",
    "ne": "shniranjan/wav2vec2-large-xlsr-300m-nepali",
    "th": "sakares/wav2vec2-large-xlsr-thai-demo",
}


def fix_code_language(translate_to, syntax="google"):
    if syntax == "google":
        # google-translator, gTTS
        replace_lang_code = {"zh": "zh-CN", "he": "iw", "zh-cn": "zh-CN"}
    elif syntax == "coqui":
        # coqui-xtts
        replace_lang_code = {"zh": "zh-cn", "zh-CN": "zh-cn"}

    new_code_lang = replace_lang_code.get(translate_to, translate_to)
    logger.debug(f"Fix code {translate_to} -> {new_code_lang}")
    return new_code_lang


bark_voices_list = {
    "de_speaker_0-Male BARK": "v2/de_speaker_0",
    "de_speaker_1-Male BARK": "v2/de_speaker_1",
    "de_speaker_2-Male BARK": "v2/de_speaker_2",
    "de_speaker_3-Female BARK": "v2/de_speaker_3",
    "de_speaker_4-Male BARK": "v2/de_speaker_4",
    "de_speaker_5-Male BARK": "v2/de_speaker_5",
    "de_speaker_6-Male BARK": "v2/de_speaker_6",
    "de_speaker_7-Male BARK": "v2/de_speaker_7",
    "de_speaker_8-Female BARK": "v2/de_speaker_8",
    "de_speaker_9-Male BARK": "v2/de_speaker_9",
    "en_speaker_0-Male BARK": "v2/en_speaker_0",
    "en_speaker_1-Male BARK": "v2/en_speaker_1",
    "en_speaker_2-Male BARK": "v2/en_speaker_2",
    "en_speaker_3-Male BARK": "v2/en_speaker_3",
    "en_speaker_4-Male BARK": "v2/en_speaker_4",
    "en_speaker_5-Male BARK": "v2/en_speaker_5",
    "en_speaker_6-Male BARK": "v2/en_speaker_6",
    "en_speaker_7-Male BARK": "v2/en_speaker_7",
    "en_speaker_8-Male BARK": "v2/en_speaker_8",
    "en_speaker_9-Female BARK": "v2/en_speaker_9",
    "es_speaker_0-Male BARK": "v2/es_speaker_0",
    "es_speaker_1-Male BARK": "v2/es_speaker_1",
    "es_speaker_2-Male BARK": "v2/es_speaker_2",
    "es_speaker_3-Male BARK": "v2/es_speaker_3",
    "es_speaker_4-Male BARK": "v2/es_speaker_4",
    "es_speaker_5-Male BARK": "v2/es_speaker_5",
    "es_speaker_6-Male BARK": "v2/es_speaker_6",
    "es_speaker_7-Male BARK": "v2/es_speaker_7",
    "es_speaker_8-Female BARK": "v2/es_speaker_8",
    "es_speaker_9-Female BARK": "v2/es_speaker_9",
    "fr_speaker_0-Male BARK": "v2/fr_speaker_0",
    "fr_speaker_1-Female BARK": "v2/fr_speaker_1",
    "fr_speaker_2-Female BARK": "v2/fr_speaker_2",
    "fr_speaker_3-Male BARK": "v2/fr_speaker_3",
    "fr_speaker_4-Male BARK": "v2/fr_speaker_4",
    "fr_speaker_5-Female BARK": "v2/fr_speaker_5",
    "fr_speaker_6-Male BARK": "v2/fr_speaker_6",
    "fr_speaker_7-Male BARK": "v2/fr_speaker_7",
    "fr_speaker_8-Male BARK": "v2/fr_speaker_8",
    "fr_speaker_9-Male BARK": "v2/fr_speaker_9",
    "hi_speaker_0-Female BARK": "v2/hi_speaker_0",
    "hi_speaker_1-Female BARK": "v2/hi_speaker_1",
    "hi_speaker_2-Male BARK": "v2/hi_speaker_2",
    "hi_speaker_3-Female BARK": "v2/hi_speaker_3",
    "hi_speaker_4-Female BARK": "v2/hi_speaker_4",
    "hi_speaker_5-Male BARK": "v2/hi_speaker_5",
    "hi_speaker_6-Male BARK": "v2/hi_speaker_6",
    "hi_speaker_7-Male BARK": "v2/hi_speaker_7",
    "hi_speaker_8-Male BARK": "v2/hi_speaker_8",
    "hi_speaker_9-Female BARK": "v2/hi_speaker_9",
    "it_speaker_0-Male BARK": "v2/it_speaker_0",
    "it_speaker_1-Male BARK": "v2/it_speaker_1",
    "it_speaker_2-Female BARK": "v2/it_speaker_2",
    "it_speaker_3-Male BARK": "v2/it_speaker_3",
    "it_speaker_4-Male BARK": "v2/it_speaker_4",
    "it_speaker_5-Male BARK": "v2/it_speaker_5",
    "it_speaker_6-Male BARK": "v2/it_speaker_6",
    "it_speaker_7-Female BARK": "v2/it_speaker_7",
    "it_speaker_8-Male BARK": "v2/it_speaker_8",
    "it_speaker_9-Female BARK": "v2/it_speaker_9",
    "ja_speaker_0-Female BARK": "v2/ja_speaker_0",
    "ja_speaker_1-Female BARK": "v2/ja_speaker_1",
    "ja_speaker_2-Male BARK": "v2/ja_speaker_2",
    "ja_speaker_3-Female BARK": "v2/ja_speaker_3",
    "ja_speaker_4-Female BARK": "v2/ja_speaker_4",
    "ja_speaker_5-Female BARK": "v2/ja_speaker_5",
    "ja_speaker_6-Male BARK": "v2/ja_speaker_6",
    "ja_speaker_7-Female BARK": "v2/ja_speaker_7",
    "ja_speaker_8-Female BARK": "v2/ja_speaker_8",
    "ja_speaker_9-Female BARK": "v2/ja_speaker_9",
    "ko_speaker_0-Female BARK": "v2/ko_speaker_0",
    "ko_speaker_1-Male BARK": "v2/ko_speaker_1",
    "ko_speaker_2-Male BARK": "v2/ko_speaker_2",
    "ko_speaker_3-Male BARK": "v2/ko_speaker_3",
    "ko_speaker_4-Male BARK": "v2/ko_speaker_4",
    "ko_speaker_5-Male BARK": "v2/ko_speaker_5",
    "ko_speaker_6-Male BARK": "v2/ko_speaker_6",
    "ko_speaker_7-Male BARK": "v2/ko_speaker_7",
    "ko_speaker_8-Male BARK": "v2/ko_speaker_8",
    "ko_speaker_9-Male BARK": "v2/ko_speaker_9",
    "pl_speaker_0-Male BARK": "v2/pl_speaker_0",
    "pl_speaker_1-Male BARK": "v2/pl_speaker_1",
    "pl_speaker_2-Male BARK": "v2/pl_speaker_2",
    "pl_speaker_3-Male BARK": "v2/pl_speaker_3",
    "pl_speaker_4-Female BARK": "v2/pl_speaker_4",
    "pl_speaker_5-Male BARK": "v2/pl_speaker_5",
    "pl_speaker_6-Female BARK": "v2/pl_speaker_6",
    "pl_speaker_7-Male BARK": "v2/pl_speaker_7",
    "pl_speaker_8-Male BARK": "v2/pl_speaker_8",
    "pl_speaker_9-Female BARK": "v2/pl_speaker_9",
    "pt_speaker_0-Male BARK": "v2/pt_speaker_0",
    "pt_speaker_1-Male BARK": "v2/pt_speaker_1",
    "pt_speaker_2-Male BARK": "v2/pt_speaker_2",
    "pt_speaker_3-Male BARK": "v2/pt_speaker_3",
    "pt_speaker_4-Male BARK": "v2/pt_speaker_4",
    "pt_speaker_5-Male BARK": "v2/pt_speaker_5",
    "pt_speaker_6-Male BARK": "v2/pt_speaker_6",
    "pt_speaker_7-Male BARK": "v2/pt_speaker_7",
    "pt_speaker_8-Male BARK": "v2/pt_speaker_8",
    "pt_speaker_9-Male BARK": "v2/pt_speaker_9",
    "ru_speaker_0-Male BARK": "v2/ru_speaker_0",
    "ru_speaker_1-Male BARK": "v2/ru_speaker_1",
    "ru_speaker_2-Male BARK": "v2/ru_speaker_2",
    "ru_speaker_3-Male BARK": "v2/ru_speaker_3",
    "ru_speaker_4-Male BARK": "v2/ru_speaker_4",
    "ru_speaker_5-Female BARK": "v2/ru_speaker_5",
    "ru_speaker_6-Female BARK": "v2/ru_speaker_6",
    "ru_speaker_7-Male BARK": "v2/ru_speaker_7",
    "ru_speaker_8-Male BARK": "v2/ru_speaker_8",
    "ru_speaker_9-Female BARK": "v2/ru_speaker_9",
    "tr_speaker_0-Male BARK": "v2/tr_speaker_0",
    "tr_speaker_1-Male BARK": "v2/tr_speaker_1",
    "tr_speaker_2-Male BARK": "v2/tr_speaker_2",
    "tr_speaker_3-Male BARK": "v2/tr_speaker_3",
    "tr_speaker_4-Female BARK": "v2/tr_speaker_4",
    "tr_speaker_5-Female BARK": "v2/tr_speaker_5",
    "tr_speaker_6-Male BARK": "v2/tr_speaker_6",
    "tr_speaker_7-Male BARK": "v2/tr_speaker_7",
    "tr_speaker_8-Male BARK": "v2/tr_speaker_8",
    "tr_speaker_9-Male BARK": "v2/tr_speaker_9",
    "zh_speaker_0-Male BARK": "v2/zh_speaker_0",
    "zh_speaker_1-Male BARK": "v2/zh_speaker_1",
    "zh_speaker_2-Male BARK": "v2/zh_speaker_2",
    "zh_speaker_3-Male BARK": "v2/zh_speaker_3",
    "zh_speaker_4-Female BARK": "v2/zh_speaker_4",
    "zh_speaker_5-Male BARK": "v2/zh_speaker_5",
    "zh_speaker_6-Female BARK": "v2/zh_speaker_6",
    "zh_speaker_7-Female BARK": "v2/zh_speaker_7",
    "zh_speaker_8-Male BARK": "v2/zh_speaker_8",
    "zh_speaker_9-Female BARK": "v2/zh_speaker_9",
}

vits_voices_list = {
    "ar-facebook-mms VITS": "facebook/mms-tts-ara",
    # 'zh-facebook-mms VITS': 'facebook/mms-tts-cmn',
    "zh_Hakka-facebook-mms VITS": "facebook/mms-tts-hak",
    "zh_MinNan-facebook-mms VITS": "facebook/mms-tts-nan",
    # 'cs-facebook-mms VITS': 'facebook/mms-tts-ces',
    # 'da-facebook-mms VITS': 'facebook/mms-tts-dan',
    "nl-facebook-mms VITS": "facebook/mms-tts-nld",
    "en-facebook-mms VITS": "facebook/mms-tts-eng",
    "fi-facebook-mms VITS": "facebook/mms-tts-fin",
    "fr-facebook-mms VITS": "facebook/mms-tts-fra",
    "de-facebook-mms VITS": "facebook/mms-tts-deu",
    "el-facebook-mms VITS": "facebook/mms-tts-ell",
    "el_Ancient-facebook-mms VITS": "facebook/mms-tts-grc",
    "he-facebook-mms VITS": "facebook/mms-tts-heb",
    "hu-facebook-mms VITS": "facebook/mms-tts-hun",
    # 'it-facebook-mms VITS': 'facebook/mms-tts-ita',
    # 'ja-facebook-mms VITS': 'facebook/mms-tts-jpn',
    "ko-facebook-mms VITS": "facebook/mms-tts-kor",
    "fa-facebook-mms VITS": "facebook/mms-tts-fas",
    "pl-facebook-mms VITS": "facebook/mms-tts-pol",
    "pt-facebook-mms VITS": "facebook/mms-tts-por",
    "ru-facebook-mms VITS": "facebook/mms-tts-rus",
    "es-facebook-mms VITS": "facebook/mms-tts-spa",
    "tr-facebook-mms VITS": "facebook/mms-tts-tur",
    "uk-facebook-mms VITS": "facebook/mms-tts-ukr",
    "ur_arabic-facebook-mms VITS": "facebook/mms-tts-urd-script_arabic",
    "ur_devanagari-facebook-mms VITS": "facebook/mms-tts-urd-script_devanagari",
    "ur_latin-facebook-mms VITS": "facebook/mms-tts-urd-script_latin",
    "vi-facebook-mms VITS": "facebook/mms-tts-vie",
    "hi-facebook-mms VITS": "facebook/mms-tts-hin",
    "hi_Fiji-facebook-mms VITS": "facebook/mms-tts-hif",
    "id-facebook-mms VITS": "facebook/mms-tts-ind",
    "bn-facebook-mms VITS": "facebook/mms-tts-ben",
    "te-facebook-mms VITS": "facebook/mms-tts-tel",
    "mr-facebook-mms VITS": "facebook/mms-tts-mar",
    "ta-facebook-mms VITS": "facebook/mms-tts-tam",
    "jw-facebook-mms VITS": "facebook/mms-tts-jav",
    "jw_Suriname-facebook-mms VITS": "facebook/mms-tts-jvn",
    "ca-facebook-mms VITS": "facebook/mms-tts-cat",
    "ne-facebook-mms VITS": "facebook/mms-tts-nep",
    "th-facebook-mms VITS": "facebook/mms-tts-tha",
    "th_Northern-facebook-mms VITS": "facebook/mms-tts-nod",
}

LANGUAGE_CODE_IN_THREE_LETTERS = {
    "Automatic detection": "aut",
    "ar": "ara",
    "zh": "chi",
    "cs": "cze",
    "da": "dan",
    "nl": "dut",
    "en": "eng",
    "fi": "fin",
    "fr": "fre",
    "de": "ger",
    "el": "gre",
    "he": "heb",
    "hu": "hun",
    "it": "ita",
    "ja": "jpn",
    "ko": "kor",
    "fa": "per",
    "pl": "pol",
    "pt": "por",
    "ru": "rus",
    "es": "spa",
    "tr": "tur",
    "uk": "ukr",
    "ur": "urd",
    "vi": "vie",
    "hi": "hin",
    "id": "ind",
    "bn": "ben",
    "te": "tel",
    "mr": "mar",
    "ta": "tam",
    "jw": "jav",
    "ca": "cat",
    "ne": "nep",
    "th": "tha",
}
